bin_addr: :8081
log_level: debug

#database_url: host=localhost, dbname=restapi_dev, user=user, password=user, sslmode=disable
store:
  host: localhost
  port: 5432
  db_name: postgres
  user_name: postgres
  password: postgres
  sslmode: disable
